export const EventsActionTypes = {
    GET_ALL_EVENTS_START: '[Events] GET_ALL_EVENTS_START',
    GET_ALL_EVENTS_SUCCESS: '[Events] GET_ALL_EVENTS_SUCCESS',
    GET_ALL_EVENTS_ERROR: '[Events] GET_ALL_EVENTS_ERROR',

    GET_EVENT_START: '[Event] GET_EVENT_START',
    GET_EVENT_SUCCESS: '[Event] GET_EVENT_SUCCESS',
    GET_EVENT_ERROR: '[Event] GET_EVENT_ERROR'
}