export const EventsActionTypes = {
    GET_ALL_EVENTS_START: '[Events] GET_ALL_EVENTS_START',
    GET_ALL_EVENTS_SUCCESS: '[Events] GET_ALL_EVENTS_SUCCESS',
    GET_ALL_EVENTS_ERROR: '[Events] GET_ALL_EVENTS_ERROR'
}