export const CreatorsActionTypes = {
    GET_ALL_CREATORS_START: '[Creators] GET_ALL_CREATORS_START',
    GET_ALL_CREATORS_SUCCESS: '[Creators] GET_ALL_CREATORS_SUCCESS',
    GET_ALL_CREATORS_ERROR: '[Creators] GET_ALL_CREATORS_ERROR',

    GET_CREATOR_START: '[Creator] GET_CREATOR_START',
    GET_CREATOR_SUCCESS: '[Creator] GET_CREATOR_SUCCESS',
    GET_CREATOR_ERROR: '[Creator] GET_CREATOR_ERROR'
}