export const CreatorsActionTypes = {
    GET_ALL_CREATORS_START: '[Creators] GET_ALL_CREATORS_START',
    GET_ALL_CREATORS_SUCCESS: '[Creators] GET_ALL_CREATORS_SUCCESS',
    GET_ALL_CREATORS_ERROR: '[Creators] GET_ALL_CREATORS_ERROR'
}