export const CharactersActionTypes = {
    GET_ALL_CHARACTERS_START: '[Characters] GET_ALL_CHARACTERS_START',
    GET_ALL_CHARACTERS_SUCCESS: '[Characters] GET_ALL_CHARACTERS_SUCCESS',
    GET_ALL_CHARACTERS_ERROR: '[Characters] GET_ALL_CHARACTERS_ERROR'
}