export const StoriesActionTypes = {
  GET_ALL_STORIES_START: "[Stories] GET_ALL_STORIES_START",
  GET_ALL_STORIES_SUCCESS: "[Stories] GET_ALL_STORIES_SUCCESS",
  GET_ALL_STORIES_ERROR: "[Stories] GET_ALL_STORIES_ERROR",

  GET_STORY_START: "[Story] GET_STORY_START",
  GET_STORY_SUCCESS: "[Story] GET_STORY_SUCCESS",
  GET_STORY_ERROR: "[Story] GET_STORY_ERROR",
};
